### ISSUE TITLE
Exclude operator not behaving?

### ISSUE THREAD

**Issue by bcorrie** [airr-community/adc-api#3]
@schristley I created an exclude operator test on array fields. It didn't behave correctly, which I expected might be an issue. But when I went to look at the exclude operator test on a normal field, it also didn't work... Bug in the reference implementation and/or VDJServer?

```
$ src/ADCtest.sh https://vdjserver.org/airr/v1 repertoire  repertoire/pass-exclude-op.json

Running test repertoire/pass-exclude-op.json
ERROR: Expected 57 != 3 records
```

**Comment by schristley** [comment]
That test passes against the reference implementation. I did do some updates to the test dataset, so you will need to reload it for some of the tests. I don't think this particular test is affected though.

```
# src/ADCtest.sh http://vdj-dev.tacc.utexas.edu:8080/airr/v1 repertoire repertoire/pass-exclude-op.json 
 
Running test repertoire/pass-exclude-op.json
INFO: Received 57 Repertoires from query
PASS: Query file repertoire/pass-exclude-op.json to http://vdj-dev.tacc.utexas.edu:8080/airr/v1/repertoire OK
```

There are a lot of bugs in the VDJServer implementation. I'm currently working on a getting a test environment setup, so that I can run the test suite against it properly.

I'd prefer if you file bugs here only for the ADC API reference implementation, and not for VDJServer. The implementations are different, so when there is a change, I have to modify both code bases. I've been keeping the reference implementation up-to-date, but I'm far behind on incorporating them into VDJServer.
